language: julia
os:
  - linux
julia:
  - 0.4
notifications:
  email: false
sudo: false
script:
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("MinMaxFilter"); Pkg.test("MinMaxFilter"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("MinMaxFilter")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
