language: julia
os:
  - linux
julia:
  - 0.3
  - 0.4
notifications:
  email: false
sudo: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("MinMaxFilter"); Pkg.test("MinMaxFilter")'
after_success:
- julia -e 'cd(Pkg.dir("MinMaxFilter")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
